# Generated by Django 5.1.3 on 2024-11-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('answer', models.TextField()),
                ('keywords', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
